/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bridge_CustomIRBridge */

#ifndef _Included_bridge_CustomIRBridge
#define _Included_bridge_CustomIRBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bridge_CustomIRBridge
 * Method:    processBinaryTree
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bridge_CustomIRBridge_processBinaryTree
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
